### VSCode REST extension
GET http://localhost:3001/api/movies

### 
GET http://localhost:3001/api/genres

###
GET http://localhost:3001/api/movies/tt0111161

###
POST http://localhost:3001/api/movies 
content-type: application/json

{
  "title": "The Shawshank Redemption",
  "year": 1994,
  "rating": 9.3,
  "genre": ["Drama"],
  "duration": "2h 22m"
}

###
PUT http://localhost:3001/api/movies/tt0111161
content-type: application/json

{
  "title": "The Shawshank Redemption",
  "year": 1996,
  "rating": 9.3,
  "genre": ["Drama"],
  "duration": "2h 22m",
  "movie_id": "tt0111161"
}

###
DELETE http://localhost:3001/api/movies/tt0111161

###
GET http://localhost:3001/api/movies/11415477